### PR TITLE
fix hide warnings

### LINKED ISSUE #3278: The Option of "Hide warning" doesn't work
Here is the snapshot.
image

### PR DESCRIPTION
**Pull request by Aniket-Engg**
fixes #3278 

This also removes the warnings count badge from the Solidity Compiler plugin icon. Warnings will still be visible in editor.

### CODE REVIEW

File: libs/remix-ui/solidity-compiler/src/lib/solidity-compiler.tsx [hunk 1]
```diff
@@ -43,7 +43,7 @@ export const SolidityCompiler = (props: SolidityCompilerProps) => {
       const hide = await api.getAppParameter('hideWarnings') as boolean || false
       setHideWarnings(hide)
     })()
-  }, [])
+  })
```
Comment (ioedeveloper) [inline libs/remix-ui/solidity-compiler/src/lib/solidity-compiler.tsx:46]: @Aniket-Engg By removing the dependency array, this useEffect will be fired every single time this component is re-rendered. I don't think it is a good solution in my opinion, we can tie the change to a variable and pass it to the dependency array. `, [hideWarnings])`

**Review by ioedeveloper — CHANGES_REQUESTED** [review]

File: libs/remix-ui/solidity-compiler/src/lib/solidity-compiler.tsx (hunk 1 above)
Comment (Aniket-Engg) [reply libs/remix-ui/solidity-compiler/src/lib/solidity-compiler.tsx:46]: I tried that. It is not solving the issue

**Review by ioedeveloper — APPROVED** [review]
