### PR TITLE
fix terminal dragbar

### LINKED ISSUE #1752: Terminal dragbar wrong behavior
Hi!

I found an issue when dragging the terminal.

## Steps to reproduce
1. Open remix ide
2. Press the toggleTerminal button
3. drag up the terminal

The drag is not center to cursor.

## Evidence

https://user-images.githubusercontent.com/62523840/141216149-6e7b0a46-8397-4a96-b5c5-097c7f423c3c.mov

### PR DESCRIPTION
**Pull request by Josel95**
fix #1752 error.

Also the code corresponding to the terminal dragbar was refactor using a hook to improve maintenance.

Thanks!

### CODE REVIEW

File: libs/remix-ui/terminal/src/lib/remix-ui-terminal.tsx [hunk 1]
```diff
@@ -78,6 +74,33 @@ export const RemixUiTerminal = (props: RemixUiTerminalProps) => {
...
+  // Check open state
+  useEffect(() => {
+    const resizeValue = isOpen ? [config.get('terminal-top-offset')] : []
+    event.trigger('resize', resizeValue)
+  }, [isOpen])
+
+  useEffect(() => {
+    leftRef.current.style.backgroundColor = isDragging ? '#007AA6' : ''
+    leftRef.current.style.border = isDragging ? '2px solid #007AA6' : ''
+  }, [isDragging])
```
Comment (ioedeveloper) [inline libs/remix-ui/terminal/src/lib/remix-ui-terminal.tsx:99]: I don't see a need for this useEffect. The logic above can be contained in the style of the element.

**Review by ioedeveloper — CHANGES_REQUESTED** [review]

**Comment by ioedeveloper** [comment]
Nice PR 🚀!

File: libs/remix-ui/terminal/src/lib/remix-ui-terminal.tsx (hunk 1 above)
Comment (LianaHus) [reply libs/remix-ui/terminal/src/lib/remix-ui-terminal.tsx:99]: can you please use theme variables/classes instead of hardcoded values for color? we have different themes, it should work for all of them

Comment (Josel95) [reply libs/remix-ui/terminal/src/lib/remix-ui-terminal.tsx]: That logic I left it as it was, anyway I already sent the changes.

There are other hardcoded colors in the code, maybe I can verify that they change according to the different themes and send a pr if necessary.

Thanks for your reviews!

**Comment by ioedeveloper** [comment]
@Josel95 Can you resolve the merge conflicts in your PR so we can proceed?

**Comment by Josel95** [comment]
> @Josel95 Can you resolve the merge conflicts in your PR so we can proceed?

Conflicts solved. 👍🏻

**Review by ryestew — COMMENTED** [review]
I am not finding much difference in the behavior of the dragbar.  So this review is not about the code refactoring.  
Here's a list of the original problems that @Josel95 described:
1. If you drag the drag bar towards the top of the page and then click the collapse terminal button and then try to drag, the dragbar jumps to its old position at the top of the page while the mouse position is at the bottom of the page.
2. Then when you click the collapse button when the mouse is at the top of the page - nothing happens on the 1st click. On the 2nd click, the terminal collapses.

So I don't see any change in the behavior from what is happening currently in remix.ethereum.org.   I assume this PR was about fixing points 1 & 2 -but I don't see the behavior changing.  Please let me know if I am missing something.

**Comment by Josel95** [comment]
Hi, @ryestew.

Yes, the pr is about fixing 1 & 2. Also I do a refactor of the code to take it more maintainable.

The steps to reproduce are:
- With the terminal in the half of the screen toggle to hide it.
- drag the terminal and will jump to the original position but is not centered with the cursor.

The state of the toggle terminal button is improved.

This is the current production behavior.

https://user-images.githubusercontent.com/62523840/147092505-d86e0478-56ab-4c39-b937-94cb80d0e55d.mov

And this are the improvements with this PR.

https://user-images.githubusercontent.com/62523840/147092700-bcce9e6c-d3e8-4cdf-93b2-6b57d3c670a1.mov

Thanks.

**Review by ryestew — APPROVED** [review]

**Review by ioedeveloper — APPROVED** [review]
