### PR TITLE
unit testing issue fixed

### LINKED ISSUE #16: Run button doesn't activate once disabled
unselecting all tests disables `Run` button and it is not activated after single test select

Related to https://github.com/ethereum/remix-project/pull/15/files#diff-14280c3cbdc5b5522924a26549bf6a27R46

### PR DESCRIPTION
**Pull request by Aniket-Engg**
fixes #16

### CODE REVIEW

File: apps/remix-ide/src/app/tabs/test-tab.js [hunk 1]
```diff
@@ -103,7 +103,7 @@ module.exports = class TestTab extends ViewPlugin {
 
     if (eChecked) {
       checkAll.checked = true
-      if ((this.readyTestsNumber === this.runningTestsNumber || this.hasBeenStopped) && document.getElementById('runTestsTabStopAction').innerText === 'Stop') {
+      if ((this.readyTestsNumber === this.runningTestsNumber || this.hasBeenStopped) && document.getElementById('runTestsTabStopAction').innerText === ' Stop') {
```
Comment (ioedeveloper) [inline apps/remix-ide/src/app/tabs/test-tab.js:106]: Instead of adding a space to the compared value, we can trim trailing spaces.
```javascript
const runBtnInnerText = document.getElementById('runTestsTabStopAction').innerText

if ((this.readyTestsNumber === this.runningTestsNumber || this.hasBeenStopped) && runBtnInnerText.trim() === 'Stop')
```
This will prevent ide from breaking when an extra space is added or removed in the future.

Comment (Aniket-Engg) [reply apps/remix-ide/src/app/tabs/test-tab.js:106]: yes, seems reasonable
