### PR TITLE
fixes ABI loading

### LINKED ISSUE #5588: Missing error handling for incorrect contract ABI, leading to a blank screen
**Describe the bug**
Whenever I try to load a contract using its ABI, if that is incorrect, we land into a blank Remix screen without any UI indication. On the dev console I see numerous errors, like: `contractabi.sort is not a function`,  `Cannot set properties of null (setting 'currentContent')`

**To Reproduce**
1. Create a new file `test.abi`
2. Paste the abi below
3. Click Deploy and run transactions icon in the left bar
4. Add any address
5. Click At Address
6. See you land into a blank screen without any error

ABI to use attached.

[abi.txt](https://github.com/user-attachments/files/18273399/abi.txt)

**Expected behavior**
It would be good to have some UI message indicating the ABI is wrong.

**Screenshots**

Screenshot from 2024-12-30 10-00-30

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: chrome
 - Version: not relevant

**Additional context**

### PR DESCRIPTION
**Pull request by Aniket-Engg**
fixes #5588

### CODE REVIEW

File: libs/remix-ui/run-tab/src/lib/actions/deploy.ts [hunk 1]
```diff
@@ -26,6 +26,8 @@ const loadContractFromAddress = (plugin: RunTab, address, confirmCb, cb) => {
     confirmCb(() => {
       let abi
       try {
+        const fileContent = plugin.editor.currentContent()
```
Comment (bunsenstraat) [inline libs/remix-ui/run-tab/src/lib/actions/deploy.ts:29]: isn't this always a string?

**Review by bunsenstraat — APPROVED** [review]
