### PR TITLE
Udapp disconnect fix

### LINKED ISSUE #5483: Switch to VM if Remix is disconnected from injected provider
Currently, the account list is empty, and the remix is in an ambiguous state.
When connection is lost Remix should switch to vm

### PR DESCRIPTION
**Pull request by joeizang**
fixes #5483

### CODE REVIEW

File: libs/remix-ui/run-tab/src/lib/run-tab.tsx [hunk 1]
```diff
@@ -235,6 +235,16 @@ export function RunTabUI(props: RunTabProps) {
     }
   }, [runTab.popup])
 
+  useEffect(() => {
+    if (runTab.selectExEnv.includes('injected') &&
```
Comment (LianaHus) [inline libs/remix-ui/run-tab/src/lib/run-tab.tsx:239]: what about wallets?

File: libs/remix-ui/run-tab/src/lib/run-tab.tsx [hunk 2]
```diff
@@ -235,6 +235,16 @@ export function RunTabUI(props: RunTabProps) {
...
+      Object.entries(runTab.accounts.loadedAccounts).length === 0 &&
+    runTab.accounts.selectedAccount.length > 0) {
+      // switch to vm-cancum because no account is loaded from injected provider
+      const context = plugin.blockchain.defaultPinnedProviders[0] // vm-cancun
```
Comment (LianaHus) [inline libs/remix-ui/run-tab/src/lib/run-tab.tsx:243]: can we load load the previously selected or it will be difficult to do?

Comment (joeizang) [reply libs/remix-ui/run-tab/src/lib/run-tab.tsx:243]: It would just require some more code to track any account that is selected and persist it outside the reach of a useEffect.

File: libs/remix-ui/run-tab/src/lib/run-tab.tsx (hunk 1 above)
Comment (joeizang) [reply libs/remix-ui/run-tab/src/lib/run-tab.tsx:239]: I am not sure I understand what you mean by wallets.

**Comment by joeizang** [comment]
The other issues with walletconnect will be addressed in a separate pr. See this issue https://github.com/ethereum/remix-project/issues/5666 @LianaHus

**Review by LianaHus — APPROVED** [review]
