### PR TITLE
removed deprecated testnets

### LINKED ISSUE #6456: artifact/contract.json file still refers to outdated testnets
**Describe the bug**
Kovan, Goerli, Ropsten are long gone but are still in our compilation result.  These should be removed.

Image

**To Reproduce**
1. Compile a file
2. to got the contract's artifact/contract_name.JSON file

### PR DESCRIPTION
**Pull request by Aniket-Engg**
fixes #6456 

kept sepolia only

### CODE REVIEW

File: apps/remix-ide/src/blockchain/execution-context.js [hunk 1]
```diff
@@ -233,10 +233,7 @@ export class ExecutionContext {
   txDetailsLink (network, hash) {
     const transactionDetailsLinks = {
       Main: 'https://www.etherscan.io/tx/',
-      Rinkeby: 'https://rinkeby.etherscan.io/tx/',
-      Ropsten: 'https://ropsten.etherscan.io/tx/',
       Sepolia: 'https://sepolia.etherscan.io/tx/',
-      Kovan: 'https://kovan.etherscan.io/tx/',
       Goerli: 'https://goerli.etherscan.io/tx/'
```
Comment (yann300) [inline apps/remix-ide/src/blockchain/execution-context.js]: Goerli is also deprecated

Comment (Aniket-Engg) [reply apps/remix-ide/src/blockchain/execution-context.js]: Ok, i will remove that too then
