### PR TITLE
fix automatic Etherscan verification

### LINKED ISSUE #6547: Info needed for etherscan and other verification services for auto verification
**Describe the bug**
If you haven't input the Etherscan API, for auto verification it is not clear where it goes.  
You just get a message like this:

Image

The printout in the terminal should have an additional line:
Etherscan verification skipped: API key not provided for auto-verification.
Go to the Settings panel input the key.

Also there are 2 places to input the etherscan api key - in the plugin and in the settings panel.  So it is confusing which one to use.

### PR DESCRIPTION
**Pull request by hsy822**
fixes #6547 #6594

### CODE REVIEW

File: apps/contract-verification/src/app/ContractVerificationPluginClient.ts [hunk 1]
```diff
@@ -123,18 +117,17 @@ export class ContractVerificationPluginClient extends PluginClient {
...
       const compilerAbstract: CompilerAbstract = compilationResult
-      const chainSettings = mergeChainSettingsWithDefaults(chainId, userSettings)
-
       const verificationPromises = []
       const verifiers: VerifierIdentifier[] = ['Sourcify', 'Etherscan', 'Blockscout', 'Routescan']
 
       for (const verifier of verifiers) {
+        if (verifier === 'Etherscan' && !effectiveApiKey) {
+          await this.call('terminal', 'log', { type: 'warn', value: 'Etherscan verification skipped: API key not provided.' })
+          await this.call('terminal', 'log', { type: 'warn', value: `Please input the API key in Remix Settings OR Contract Verification Plugin Settings.` })
```
Comment (ryestew) [inline apps/contract-verification/src/app/ContractVerificationPluginClient.ts]: Please edit to:
Please input the API key in Remix Settings - Connected Services OR Contract Verification Plugin Settings
