### PR TITLE
astwalker improved

### LINKED ISSUE #418: solidity locals and states don't show up when debugging
This happens in currently in remix-alpha.
Steps to reproduce:
 - Deploy the ballot - https://gist.github.com/yann300/e8838a857a81ccc2092a5e61fa7f3e3c
 - Execute `delegate`
 - Start debugging: the locals and state panel is hidden.

### PR DESCRIPTION
**Pull request by Aniket-Engg**
fixes #418

### CODE REVIEW

**Review by yann300 — APPROVED** [review]

File: libs/remix-debug/src/source/astWalker.js [hunk 1]
```diff
@@ -21,13 +21,15 @@ AstWalker.prototype.walk = function (ast, callback) {
...
     callback['*'] = function () { return true }
   }
-  const nodes = ast.nodes || (ast.body && ast.body.statements) || ast.declarations
-  if(ast.body && ast.initializationExpression) // 'for' loop handling
-    nodes.push(ast.initializationExpression)
-  if (manageCallBack(ast, callback) && nodes && nodes.length > 0) {
-    for (let k in nodes) {
-      const child = nodes[k]
-      this.walk(child, callback)
+  if(ast){
```
Comment (yann300) [inline libs/remix-debug/src/source/astWalker.js:24]: I think that is missing some spaces.
