### PR TITLE
handle similar names location

### LINKED ISSUE #799: Static analysis warning location
For contract:
```
// SPDX-License-Identifier: MIT

pragma solidity 0.8.0;  
contract am {
    uint a;
    uint A;
    uint aaaa;
    uint aaaaa;
    uint aaaza;
    function aa()public returns(uint) {}
}
```

Warning locations are wrong.

Screenshot 2021-01-27 at 4 37 36 PM

cc: @LianaHus

### PR DESCRIPTION
**Pull request by Aniket-Engg**
fixes #799 

Previous Analysis:
For each method, we pick state variables and local variable and if there are similar variable, show warning for method by highlighting complete method.

Flaw:
If there are two similar state variables, warning will be shown for each method even if it is not used in it or even if method is not implemented.

Updated Analysis:

After finding similar variables, analyzer walks function body and check if one of the similar variable name is declared or used in the method and highlights variable location.

### CODE REVIEW

File: libs/remix-analyzer/src/solidity-analyzer/modules/similarVariableNames.ts [hunk 1]
```diff
@@ -43,13 +44,25 @@ export default class similarVariableNames implements AnalyzerModule {
...
         }
-
         const vars: string[] = this.getFunctionVariables(contract, func).map(getDeclaredVariableName)
         this.findSimilarVarNames(vars).map((sim) => {
-          warnings.push({
-            warning: `${funcName} : Variables have very similar names "${sim.var1}" and "${sim.var2}". ${hasModifiersComments} ${multipleContractsWithSameNameComments}`,
-            location: func.node['src']
-          })
+          // check if function is implemented
+          if(func.node.implemented) {
```
Comment (LianaHus) [inline libs/remix-analyzer/src/solidity-analyzer/modules/similarVariableNames.ts:50]: I'm not sure if we have a linter setup here but you need a space after if.

Comment (Aniket-Engg) [reply libs/remix-analyzer/src/solidity-analyzer/modules/similarVariableNames.ts:50]: Yeah. We have the issue opened https://github.com/ethereum/remix-project/issues/559 . If you are fine, can we do this with that issue implementation?

**Review by LianaHus — APPROVED** [review]

File: apps/remix-ide-e2e/src/tests/staticAnalysis.test.ts [hunk 2]
```diff
@@ -43,7 +43,8 @@ function runTests (browser: NightwatchBrowser) {
     .waitForElementPresent('#staticanalysisresult .warning', 2000, true, function () {
       listSelectorContains(['Use of tx.origin',
         'Fallback function of contract TooMuchGas requires too much gas',
-        'TooMuchGas.() : Variables have very similar names "test" and "test1".'],
+        'TooMuchGas.() : Variables have very similar names "test" and "test1".',
+        'TooMuchGas.() : Variables have very similar names "test" and "test1".' ],
```
Comment (yann300) [inline apps/remix-ide-e2e/src/tests/staticAnalysis.test.ts:47]: why is that duplicated?

File: libs/remix-analyzer/test/analysis/staticAnalysisIntegration-test-0.5.0.ts [hunk 3]
```diff
@@ -278,23 +278,23 @@ test('Integration test similarVariableNames module', function (t: test.Test) {
   const lengthCheck: Record<string, number> = {
     'KingOfTheEtherThrone.sol': 0,
     'assembly.sol': 0,
-    'ballot.sol': 2,
-    'ballot_reentrant.sol': 11,
+    'ballot.sol': 7,
+    'ballot_reentrant.sol': 40,
```
Comment (yann300) [inline libs/remix-analyzer/test/analysis/staticAnalysisIntegration-test-0.5.0.ts:282]: so many?

File: apps/remix-ide-e2e/src/tests/staticAnalysis.test.ts (hunk 2 above)
Comment (Aniket-Engg) [reply apps/remix-ide-e2e/src/tests/staticAnalysis.test.ts:47]: Because now we get warning for each similar variable name usage. So we will get one warning for `test` and another for `test1`

File: libs/remix-analyzer/test/analysis/staticAnalysisIntegration-test-0.5.0.ts (hunk 3 above)
Comment (Aniket-Engg) [reply libs/remix-analyzer/test/analysis/staticAnalysisIntegration-test-0.5.0.ts:282]: Yes. As explained in PR description, now we get waring for each similar variable name usage, previous it was for a method only even if it is using similar variable once or 100 times.

**Review by yann300 — APPROVED** [review]
