### PR TITLE
fix git checkout branch

### LINKED ISSUE #3086: Git checkout branch issues
- [ ] If a new workspace created as git workspace, newly created branches are not visible in the dropdown to checkout
- [ ] If a repo is cloned, `view all branches` from branches dropdown is clicked, it opens Dgit but clears URL params. Also ensure, if Dgit show relevant details
- [ ] If a cloned repo does not contain `main` branch, still in dropdown `main` branch is selected

### PR DESCRIPTION
**Pull request by Aniket-Engg**
fixes 2 and 3 of  #3086

### CODE REVIEW

**Review by yann300 — APPROVED** [review]

File: libs/remix-ui/workspace/src/lib/actions/workspace.ts [hunk 1]
```diff
@@ -68,8 +68,12 @@ export const createWorkspace = async (workspaceName: string, workspaceTemplateNa
     await plugin.workspaceCreated(workspaceName)
 
     if (isGitRepo) {
-      await plugin.call('dGitProvider', 'init', { branch: 'main' })
-      dispatch(setCurrentWorkspaceCurrentBranch('main'))
+      const workspacesPath = plugin.fileProviders.workspace.workspacesPath
+      const allBranches = await getGitRepoBranches(workspacesPath + '/' + workspaceName)
```
Comment (yann300) [inline libs/remix-ui/workspace/src/lib/actions/workspace.ts:72]: perhaps we should default to `main` if `allBranches` is empty

Comment (Aniket-Engg) [reply libs/remix-ui/workspace/src/lib/actions/workspace.ts:72]: ok, this is updated
