### PR TITLE
show hh logs for EVM revert

### LINKED ISSUE #1615: console.log is not printed for test if transaction fails with revert in SUT plugin

### PR DESCRIPTION
**Pull request by Aniket-Engg**
fixes #1615

### CODE REVIEW

File: libs/remix-tests/src/testRunner.ts [hunk 1]
```diff
@@ -377,6 +377,11 @@ export function runTest (testName: string, testObject: any, contractDetails: Com
           context: testName,
           web3
         }
+        if (err.message.includes('Transaction has been reverted by the EVM')) {
```
Comment (yann300) [inline libs/remix-tests/src/testRunner.ts:380]: even if the transaction failed, you should be able to get a receipt.. it looks like this will break as soon as the error label change. but does seem we can do better..

**Review by yann300 — APPROVED** [review]

File: libs/remix-tests/src/testRunner.ts (hunk 1 above)
Comment (Aniket-Engg) [reply libs/remix-tests/src/testRunner.ts:380]: Yes, according to current web3 implementation, we don't get tx hash on error
