### PR TITLE
fix static analysis event listen issue

### LINKED ISSUE #1400: Static Analysis Plugin Not working After Deactivation and Re-activation
#### Steps To Reproduce
- compile file 
- analysis will be shown
- switch workspace
- decativate and activate again
- then compile again
**compilation event doesn’t seem to be received by the plugin**

### PR DESCRIPTION
**Pull request by Aniket-Engg**
fixes #1400

### CODE REVIEW

File: libs/remix-ui/static-analyser/src/lib/remix-ui-static-analyser.tsx [hunk 1]
```diff
@@ -65,7 +65,7 @@ export const RemixUiStaticAnalyser = (props: RemixUiStaticAnalyserProps) => {
 
   useEffect(() => {
     compilation(props.analysisModule, dispatch)
-  }, [])
+  }, [props])
```
Comment (ioedeveloper) [inline libs/remix-ui/static-analyser/src/lib/remix-ui-static-analyser.tsx:68]: I think it is better to listen on props.analysisModule instead.

Comment (Aniket-Engg) [reply libs/remix-ui/static-analyser/src/lib/remix-ui-static-analyser.tsx:68]: I tried, this `useEffect` was not triggered with that too

**Review by ioedeveloper — APPROVED** [review]
