### PR TITLE
fix all tabs closing

### LINKED ISSUE #2344: Closing all the opened tabs does not go to empty page rather still shows the last closed tab content
1. Close all the tabs in the editor.
2. the content is still shown on the editor section of the last closed tab.
3. when editing this file does not save it to the file.

### PR DESCRIPTION
**Pull request by Aniket-Engg**
fixes #2344

### CODE REVIEW

File: apps/remix-ide/src/app/panels/tab-proxy.js [hunk 1]
```diff
@@ -153,6 +153,10 @@ export class TabProxy extends Plugin {
           displayName,
           () => this.emit('switchApp', name),
           () => {
+            if(name === 'home' && this.loadedTabs.length === 1 && this.loadedTabs[0].id === "home") {
```
Comment (LianaHus) [inline apps/remix-ide/src/app/panels/tab-proxy.js:156]: please add a space after 'if'

**Review by yann300 — APPROVED** [review]
