### PR TITLE
fix for injected web3 call

### LINKED ISSUE #1282: [Bug] Contract call failing in Remix UI (failing to read on-chain data)
I was trying to call my contract that's deployed to Kovan, but I kept getting this Metamask error in my browser console:
``Invalid params: unknown field \`timestamp\`, expected one of \`type\`, \`from\`, \`to\`, \`gasPrice\`, \`gas\`, \`value\`, \`data\`, \`nonce\`, \`accessList\`.``
I tried with my Kovan Infura provider instead on Metamask, still got the same error:
``call to PriceConsumerV3.getLatestPrice errored: Error: Returned error: Invalid params: unknown field `timestamp`, expected one of `type`, `from`, `to`, `gasPrice`, `gas`, `value`, `data`, `nonce`, `accessList`. 
``
I double-checked that the network was switched to Kovan for both times.

The contract call works just fine on Etherscan's contract UI though: https://kovan.etherscan.io/address/0x31C09Eaf8bA8D8FC9Ab044896F870cD737617FF6#readContract

Contract code is available on that same Etherscan link above.

### PR DESCRIPTION
**Pull request by Aniket-Engg**
fixes #1282

### CODE REVIEW

**Review by yann300 — APPROVED** [review]

File: libs/remix-lib/src/execution/txRunnerWeb3.ts [hunk 1]
```diff
@@ -72,13 +72,19 @@ export class TxRunnerWeb3 {
...
       tx['timestamp'] = timestamp
-      return this.getWeb3().eth.call(tx, function (error, result: any) {
-        if (error) return callback(error)
-        callback(null, {
-          result: result
+      return this._api.detectNetwork((err, network) => {
+        if (err) {
+          console.log(err)
+          return
+        } else if (network && network.name === 'Kovan') delete tx['timestamp']
```
Comment (yann300) [inline libs/remix-lib/src/execution/txRunnerWeb3.ts:81]: could you add a comment for explaining why we are removing the timestamp only for kovan?

Comment (Aniket-Engg) [reply libs/remix-lib/src/execution/txRunnerWeb3.ts:81]: sure

**Review by yann300 — APPROVED** [review]

File: libs/remix-lib/src/execution/txRunnerWeb3.ts (hunk 1 above)
Comment (Bingyy) [reply libs/remix-lib/src/execution/txRunnerWeb3.ts:84]: Do we need to upgrade metamask to use this updated code?
