### PR TITLE
fix: store invite token in Registry before URL cleanup

### LINKED ISSUE #7053: Cloud workspace sync issue
Image

### PR DESCRIPTION
**Pull request by bunsenstraat**
The invite token wasn't properly passed on to the login modal for use when logging in with email. 
Removed 'recent workspaces' because we need to refactor that with cloud on/off states. 

also fixes migration of workspaces dialog not showing up

fixes https://github.com/remix-project-org/remix-project/issues/7053

### CODE REVIEW

File: libs/remix-ui/home-tab/src/lib/components/homeTabRecentWorkspaces.tsx [hunk 1]
```diff
@@ -101,6 +101,8 @@ function HomeTabRecentWorkspaces({ plugin }: HomeTabFileProps) {
     setLoadingWorkspace(null)
   }
 
+  return null
```
Comment (Aniket-Engg) [inline libs/remix-ui/home-tab/src/lib/components/homeTabRecentWorkspaces.tsx:104]: Can you add a comment explaining, this is disabling the recent workspaces feature?

File: apps/remix-ide/src/app/plugins/invitation-manager-plugin.tsx [hunk 2]
```diff
@@ -274,21 +275,21 @@ export class InvitationManagerPlugin extends Plugin {
...
   private async checkUrlForInvite(): Promise<void> {
-    // Check query params first (?invite= or ?invite_token=)
-    const params = new URLSearchParams(window.location.search)
-    const queryToken = params.get('invite') || params.get('invite_token')
+    // Read invite token from Registry (set early by app.ts) so it survives URL
+    // param cleanup.  Fall back to reading from the URL directly.
+    let queryToken: string | null = null
+    try {
+      const entry = Registry.getInstance().get('inviteToken')
+      console.log('[InvitationManager] Invite token from Registry on URL check:', entry)
```
Comment (Aniket-Engg) [inline apps/remix-ide/src/app/plugins/invitation-manager-plugin.tsx]: remove log

**Review by Aniket-Engg — APPROVED** [review]
